# Invite your own bot to your server
# Get the bot token and channel id
# Replace YOUR_BOT_TOKEN and YOUR_DISCORD_CHANNEL_ID with your own bot token and channel id

bot-token : "YOUR_BOT_TOKEN"
channel-id : "YOUR_DISCORD_CHANNEL_ID"
guild-id : "YOUR_DISCORD_GUILD_ID"